### PR TITLE
tunnel: fix error and WebSocket EOF handling

### LINKED ISSUE #95: tunnel: first a few connections not working after localproxy reconnect
Not sure which of the server and source/destination client is causing it.
e.g. first two ssh sessions are failed to be proxied, but after them works well

### PR DESCRIPTION
**Pull request by at-wat**
fix #95

### CODE REVIEW

File: tunnel/proxy.go [hunk 1]
```diff
@@ -87,9 +87,9 @@ type ErrorHandler interface {
 	HandleError(error)
 }
 
-type errorHandlerFunc func(error)
+type ErrorHandlerFunc func(error)
```
Comment (sqbot) [inline tunnel/proxy.go:90]: **[golint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
exported type ErrorHandlerFunc should have comment or be unexported

File: tunnel/proxy.go [hunk 2]
```diff
@@ -87,9 +87,9 @@ type ErrorHandler interface {
...
 
-func (f errorHandlerFunc) HandleError(err error) {
+func (f ErrorHandlerFunc) HandleError(err error) {
```
Comment (sqbot) [inline tunnel/proxy.go:92]: **[golint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
exported method ErrorHandlerFunc.HandleError should have comment or be unexported

File: tunnel/msg/helper.go [hunk 3]
```diff
@@ -0,0 +1,24 @@
+package msg
+
+import (
+	"io"
+
+	"google.golang.org/protobuf/proto"
+)
+
+func WriteMessage(w io.Writer, m *Message) error {
```
Comment (sqbot) [inline tunnel/msg/helper.go:9]: **[golint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub>
exported function WriteMessage should have comment or be unexported

**Comment by at-wat** [comment]
@kamatama41 please take a look
